# Nix-sops secrets configuration
keys:
  # - &hosts
  #   - &framework age1dd46w7resazwynqq3gwlkxsupuje8h8qmuf0ljdgap6dywqhfqfq6amj6v
  #   - &ncase
  - &users:
    - &jorrit age1cxsymwqxq4hzvajcxmuv8m7yuslqa0rhnvkxv3ujkqrua7rngy8shhcw0m
creation_rules:
  # - path_regex: hosts/framework/secrets.yaml$
  #   key_groups:
  #   - age:
  #     - *framework
  - path_regex: users/jorrit/secrets.yaml$
    key_groups:
    - age:
      - *jorrit