# Nix-sops secrets configuration
# TODO Add ncase
keys:
  - &hosts:
    # - &framework age1d8mf30p85sdpytfg6dptn9crsxgx56e5kvzp8vl54v247sdh0q5qr63fjz
  - &users:
    - &jorrit age12hanketyv325jg8llm0tedcxred4datv6ysqgmfmzaxcclvuwsnqld5zrl
creation_rules:
  - path_regex: hosts/secrets.yaml$
    key_groups:
    - age:
      # - *framework
  - path_regex: users/jorrit/secrets.yaml$
    key_groups:
    - age:
      - *jorrit